### ISSUE TITLE
Switch ListView to FlatList?

### ISSUE THREAD

**Issue by douglasjunior** [ldn0x7dc/react-native-view-pager#10]
Thanks for keeping so many react native libraries, great work.

I'd like to use your image gallery, however its view pager uses ListView, and the ListView has performance issues.

Do you have plans to switch ListView to FlatList?

**Comment by msageryd** [comment]
Unfortunately ldn0x7dc seems to have abandoned his great work. There are a bunch of forks that solves several issues. I for one am waiting eagerly on version 2 from these guys: https://github.com/archriss/react-native-image-gallery

They seem to have solved many issues, including listview/flatlist.

**Comment by douglasjunior** [comment]
Thanks for the tip, but they also use this same ViewPager with ListView. :/

https://github.com/archriss/react-native-image-gallery/blob/4681ac68d83ba4e167c37bcc0efabc7f18eb3135/library/Gallery.js#L5

**Comment by msageryd** [comment]
That's fixed in version 2, which seems to be released soon:
https://github.com/archriss/react-native-image-gallery/pull/15

https://github.com/archriss/react-native-image-gallery/pull/15/commits/b63a6c7df48ecfaef40edeaea0d57e8c7c9cecb7

**Comment by douglasjunior** [comment]
Great, thanks!
